### PR TITLE
Restore import routes

### LINKED ISSUE #384: Add routes for import

### PR DESCRIPTION
**Pull request by astupak**
Closes #384

### CODE REVIEW

**Comment by zouxuoz** [comment]
@astupak import's pages have static headers, can you add headers as React components?

**Comment by astupak** [comment]
@zouxuoz Done

**Comment by radiansz** [comment]
LGTM

**Comment by zouxuoz** [comment]
@astupak rebase it from webpack-react

**Comment by zouxuoz** [comment]
lgtm

**Comment by radiansz** [comment]
lgtm

**Pull request merged**
