### PR TITLE
Rework field and button names, add field for showing an error. Add tests

### PR DESCRIPTION
**Pull request by radiansz**
It's one way to implement Message for showing errors(specifically for showing some general error message after submit). Other ways for implementing can be "Field style" container which basically would pass errors to the prop-component:
```
<Message component="ErrorMessage"/>
```
and higher order component which would connect passed component to the context:
```
withContext(ErrorMessage)
```
These two approaches will require creating another component, but more flexible.
Any thought which approach would be the best? @rosendi @zouxuoz

### CODE REVIEW

**Comment by rosendi** [comment]
I really like the variant with HoC. Another idea is to merge the `Button` and `Message` containers, i.e. it's just a bridge to the form context. am I right?

**Comment by rosendi** [comment]
may be we can call the connector `withForm`

**Comment by radiansz** [comment]
I like the idea of HoC `withForm', which will be used for implementing `Button` and `Message`. Let's do it then

**Comment by rosendi** [comment]
`Form` `withForm`, `InputField`, `SubmitField`, `ErrorField`? yep? this way we avoid Button as FormButton? Since it isn't alway a button :-)

**Comment by radiansz** [comment]
I thought about `withForm` as of HoC for connecting external components to the form context. I'm not sure we need `SubmitField`, `ErrorField` since component which we would pass in it will be depend on params which `(Submit|Error)Field` passes.

**Comment by rosendi** [comment]
radiansz Yes, you are right! Give me a final small example for simple form...

**Comment by radiansz** [comment]
I see roughly like this:
```
const ErrorMessageFunc = (props, { errors }) => (
  errors._global && <span>errors._global</span> || null
);

const SubmitButtonFunc = (props, { submitting }) => (
  <Button>{submitting ? 'submittimg' : 'submit'}</Button>
);

const ErrorMessage = withForm(ErrorMessageFunc);
const SubmitButton = withForm(SubmitButtonFunc);

const SomeForm = ({ onSubmit, onError }) => (
  <Form onSubmit={onSubmit} onError={onError}>
    <Field component="InputText" name="someInput" />
    <ErrorMessage />
    <SubmitButton />
  </Form>
);  
```
With `SubmitButton` and `ErrorMessage` as exported components.

**Comment by rosendi** [comment]
@radiansz  awesome!

**Comment by rosendi** [comment]
LGTM

**Comment by zouxuoz** [comment]
lgtm

**Pull request merged**
